Integrated project with `cdash`, for aggregating `ctest` data, updated cmake workflow and README (#9)
* Integrated project with `cdash`, for aggregating `ctest` data, updated cmake workflow and README

- Create `CTestConfig.cmake` for configuring `ctest` and dashboard options

- Create `MemoryCheck.cmake` for setting up `ctest` memory tests

- Rename `ClangTidy.cmake` to `CleanCompileCommands.cmake`

- Add project `CDash` url to README

- Add `cmake_generator` to CI_CD matrix

- Setup cmake memory checking

* Quote ctest arguments to handle spaced words

* Fix typo in `CI-CD.cmake`

* Edited CI/CD ctest script to run memory test only when memory checker is defined and moved step for installing memory checker to run before the dashboard step

* Completed CDash intergration, refactored cmake workflow and updated README

- Create `CTestScript.cmake` as a configuration file for the ctest script.

- Create `CleanCompileCommandsRunner.cmake` for cross platform compile commands cleaning

- Create `GetCommandLineVariables` for collecting `-D` variables in a variable

- Add logic in `CMakeLists.txt` to stop execution after necessary variables are gotten and ctest script has been generated

- Add cmake option `GENERATE_CTEST_SCRIPT` for generating the ctest script

- Rename `CI-CD.cmake` to `CTestScript.cmake`

- Delete unused `ClangTidy.cmake` and `CI-CD.cmake`

- Remove unnecessary variables from `MemoryCheck.cmake`

- Add instructions to README on generating and using ctest script

- Remove memory leak test steps for from cmake workflow, as address sanitizer support is complete and will be used

- Remove build and test steps from cmake workflow

- Add ctest dashboard step to cmake workflow, for using ctest as workflow runner and cdash client

- Add upload cdash artifacts step to cmake workflow to upload xml files generated by ctest script

* Removed meory checker install step and added option to generate ctest script to cmake configure step

* Reenable configure step in cmake workflow and enabled printing of `CMakeCache.txt` in debu step

* Rename env variable `CDASH_AUTH_TOKEN` to `CDASH_TOKEN` and fixed path to cdash files to upload

* Changed `CDASH_ARTIFACT_NAME` to fix clashing with `ARTIFACT_NAME` and renamed `ARTIFACT_NAME` to `BUILD_ARTIFACT_NAME`

* Debugging Windows, again :(

* Removed bad flag from configure step, trimmed output of debug step, added print statements to track ctest script creation and fixed some bugs

* Write up a hack for Windows

* Added quoting for filepath variables parsed by `GetCommandLineVariales.cmake`

* Added escaped quotes to filepaths

* Trying once more

* Restore `GetCommandLinevariables.cmake` to its original state. Disabled other os workflow. Quote compiler pat for Windows. Still debugging

* Debugging

* Debugging

* Debugging

* Debugging

* Debugging :(

* Trying to fix bugs

* On bug duty

* So close

* Debugging

* Made `CTest` be included at top of cmake config, corrected syntax and spelling mistakes, also removed some debug messages

* Made some tweaks and probably fixed the Windows issu

- Set `CTEST_USE_LAUNCHERS` only when the cmake generator uses make or ninja

- Moved escaping of `CMAKE_ARGS` spaces to the toplevel configurai

* Made a few tweaks and modified cmake workflow

- Comment out verbose comands in debug step in cmake workflow, to reduce output

- Remove unnecessary directory creation commands in cmake workflow

- Change setup step id to `setup` in cmake workflow

- Fix syntax error in cmake workflow

- Make error message more descriptive in ctest script

- Restore other OSes n matrix in `CI_CD` workflow job

- Remove unnecessary include option in `CI_CD` job

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -27,9 +27,13 @@ jobs:
     runs-on: ${{matrix.os}}
 
     env:
-      IS_MAIN_BRANCH: ${{ (github.event_name == 'push' && github.head_ref == 'main') ||  github.ref_name == 'main'  }}
+      CDASH_TOKEN: ${{ secrets.CDASH_TOKEN }}
       BUILD_DIR: ${{github.workspace}}/build
-      ARTIFACT_NAME: CLipt-${{matrix.os}}-${{matrix.c_compiler}}-${{matrix.build_type}}
+      IS_MAIN_BRANCH: ${{ (github.event_name == 'push' && github.head_ref == 'main') ||  github.ref_name == 'main'  }}
+
+      BUILD_ARTIFACT_NAME: CLipt-${{matrix.os}}-${{matrix.c_compiler}}-${{matrix.build_type}}
+      CDASH_ARTIFACT_NAME: CDash-${{matrix.os}}-${{matrix.c_compiler}}-${{matrix.build_type}}
+
       REPL_EXECUTABLE: ${{github.workspace}}/build/bin/${{matrix.build_type}}/cliptr
       TEST_EXECUTABLE: ${{github.workspace}}/build/bin/${{matrix.build_type}}/test_suite
 
@@ -41,26 +45,23 @@ jobs:
         os: [ubuntu-latest, macos-latest, windows-latest]
         build_type: [Debug]
         c_compiler: [gcc, clang, cl]
-        include:
-          - os: windows-latest
-            c_compiler: cl
-          - os: ubuntu-latest
-            c_compiler: gcc
-          - os: ubuntu-latest
-            c_compiler: clang
-          - os: macos-latest
-            c_compiler: gcc
-          - os: macos-latest
-            c_compiler: clang
+        cmake_generator: ["Unix Makefiles", "Visual Studio 17 2022"]
+
         exclude:
-          - os: windows-latest
-            c_compiler: gcc
-          - os: windows-latest
-            c_compiler: clang
           - os: ubuntu-latest
             c_compiler: cl
           - os: macos-latest
             c_compiler: cl
+          - os: ubuntu-latest
+            cmake_generator: "Visual Studio 17 2022"
+          - os: macos-latest
+            cmake_generator: "Visual Studio 17 2022"
+          - os: windows-latest
+            cmake_generator: "Unix Makefiles"
+          - os: windows-latest
+            c_compiler: gcc
+          - os: windows-latest
+            c_compiler: clang
 
     steps:
     - name: Checkout repo
@@ -70,8 +71,7 @@ jobs:
     - name: Setup
       # Turn repeated input strings (such as the build output directory) into step outputs.
       # These step outputs can be used throughout the workflow file.
-      id: strings
-      shell: bash
+      id: setup
       run: |
         mkdir -p "${{github.workspace}}/build/logs"
 
@@ -115,24 +115,14 @@ jobs:
         -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
         -DCMAKE_C_COMPILER=${{matrix.c_compiler}}
         -DENABLE_CLANG_TIDY=ON -DCLANG_TIDY_WARNINGS_AS_ERRORS=${{((env.IS_MAIN_BRANCH == 'true') && 'ON') || 'OFF'}}
-        -DENABLE_ASAN=ON
+        -DENABLE_ASAN=ON -DGENERATE_CTEST_SCRIPT=ON
 
 
-    - name: Build
-      id: build
-      # Build your program with the given configuration. Note that --config is needed because
-      # the default Windows generator is a multi-config generator (Visual Studio generator).
-      run: cmake --build ${{env.BUILD_DIR}} --config ${{matrix.build_type}}
-
-
-    - name: Test
-      id: test
-      # Execute tests defined by the CMake configuration. Note that --build-config is needed because
-      # the default Windows generator is a multi-config generator (Visual Studio generator).
-      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
-      working-directory: ${{env.BUILD_DIR}}
+    - name: CTest Dashboard Client (Continuous)
+      id: ctest-dashboard
+      working-directory: ${{github.workspace}}
       run: |
-        ctest --output-on-failure --build-config ${{matrix.build_type}}
+        ctest -VV -S build/CTestScript.cmake --output-on-failure -DCDASH_MODEL=Continuous
 
 
     - name: Pack
@@ -143,31 +133,32 @@ jobs:
 
 
     - name: Debug Job
-      # If the build or tests failed, print relevant information to help debugging.
-      if: ${{ always() && (steps.pack.outcome == 'failure' || steps.test.outcome == 'failure' || steps.build.outcome == 'failure') }}
+      # If the ctest dashboard workflow failed, print relevant information to help debugging.
+      if: ${{ always() && (steps.configure.outcome == 'failure' || steps.pack.outcome == 'failure' || steps.ctest-dashboard.outcome == 'failure') }}
       working-directory: ${{env.BUILD_DIR}}
       run: |
-        echo ""
-        echo "==== Path ===="
-        echo "${{runner.os == 'Windows' && '$env:PATH' || '$PATH'}}"
-        echo "=============="
-        echo ""
-        echo ""
         echo "===== Env ====="
-        echo "${{runner.os == 'Windows' && '$env' || '$(env)'}}"
+        echo "${{runner.os == 'Windows' && 'Get-ChildItem Env:' || 'env'}}"
         echo "================"
         echo ""
         echo ""
         echo "===== Build Directory ====="
-        ls && mkdir -p Testing Packaging
-        ls -R "bin"
-        ls -R "lib"
-        ls -R "Testing"
-        ls -R "Packaging"
+        ls
+        ls -R "bin" || true
+        ls -R "lib" || true
+        ls -R "Testing" || true
+        ls -R "Packaging" || true
         echo "==========================="
         echo ""
-        echo "==== Compile Test ===="
-        ${{matrix.c_compiler}} -v -E ../src/language/utils.c -I../include
+        echo ""
+        # echo "==== CMake Cache ===="
+        # cat "CTestScript.cmake" || true
+        # echo "====================="
+        # echo ""
+        # echo ""
+        # echo "==== Compile Test ===="
+        # ${{matrix.c_compiler}} ${{runner.os == 'Windows' && '/VERBOSE' || '-v'}} -E ../src/language/utils.c
+        # echo "======================"
 
 
     - name: Upload build artifacts
@@ -175,36 +166,18 @@ jobs:
       if: ${{ always() && steps.pack.outcome == 'success' }}
       uses: actions/upload-artifact@v4
       with:
-        name: ${{env.ARTIFACT_NAME}}
+        name: ${{env.BUILD_ARTIFACT_NAME}}
         path: ${{env.BUILD_DIR}}/Packaging/*.*
         retention-days: 7
         if-no-files-found: error
 
 
-    # Run memory leak tests
-    - name: Install Valgrind (Linux) or DrMemory (Windows)
-      uses: ConorMacBride/install-package@v1
+    - name: Upload cdash artifacts
+      # Upload cdash files
+      if: ${{ always() && steps.ctest-dashboard.outcome == 'success' }}
+      uses: actions/upload-artifact@v4
       with:
-        apt: valgrind
-        # choco: drmemory
-
-    - name: Run memory leak tests (Linux)
-      working-directory: ${{env.BUILD_DIR}}
-      if: runner.os == 'Linux'
-      run: |
-        valgrind --leak-check=full --show-leak-kinds=all -s ctest --build-config ${{matrix.build_type}}
-
-    - name: Run memory leak tests (MacOS)
-      working-directory: ${{env.BUILD_DIR}}
-      if: runner.os == 'macOS'
-      run: |
-        MallocStackLogging=1 leaks -atExit -- ctest --build-config ${{matrix.build_type}}
-
-    - name: Run memory leak tests (Windows)
-      working-directory: ${{env.BUILD_DIR}}
-      if: runner.os == 'Windows' && false
-      #drmemory -batch -leaks_only -logdir ${{env.BUILD_DIR}}/logs -- ctest --build-config ${{matrix.build_type}}
-      run: |
-        drmemory -verbose 2 -leaks_only -no_count_leaks -no_track_allocs -logdir ${{env.BUILD_DIR}}/logs/DrMemory -- ctest --build-config ${{matrix.build_type}}
-        echo "\n\nDrMemory Logs: \n"
-        cat ${{env.BUILD_DIR}}/logs/DrMemory/DrMemory-*
+        name: ${{env.CDASH_ARTIFACT_NAME}}
+        path: ${{env.BUILD_DIR}}/Testing/*/*.xml
+        retention-days: 7
+        if-no-files-found: error
